
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.TableModel;
import net.proteanit.sql.DbUtils;

/**
 *version 0.4245
 * @author Denizcan
 */

public class Frame extends javax.swing.JFrame {
    public static Connection conn;
   
    
    GridBagLayout layout = new GridBagLayout();
    UserInfo p1;
    ItemInfo p2;
    WelcomePanel p3;
   
    
    public Frame() {
       
        setTitle("PcBuild Managment tool");
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
       
        
        initComponents();
        p1=new UserInfo();
        p2 = new ItemInfo();
        p3 = new WelcomePanel();
        p1.setVisible(false);
        p2.setVisible(false);
        p3.setVisible(true);
        DynamicPanel.setLayout(layout);
        GridBagConstraints c = new GridBagConstraints();
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p3,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p1,c);
        c.gridx=0;
        c.gridy=0;
        DynamicPanel.add(p2,c);
        
        
        
       
        UserButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
           p1.setVisible(true);
           p2.setVisible(false);
           p3.setVisible(false);
        }
    });
        

         ItemButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          p1.setVisible(false);
           p2.setVisible(true);
           p3.setVisible(false);
        }
    });
    
        MainMenuButton.addActionListener(new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
          p1.setVisible(false);
          p2.setVisible(false);
          p3.setVisible(true);
        }
    });
         
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainpanel = new javax.swing.JPanel();
        LeftPanel = new javax.swing.JPanel();
        UserButton = new javax.swing.JButton();
        ItemButton = new javax.swing.JButton();
        BuildNo = new javax.swing.JLabel();
        MainMenuButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        DynamicPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1210, 700));
        setSize(new java.awt.Dimension(1230, 720));

        mainpanel.setBackground(new java.awt.Color(204, 204, 0));

        LeftPanel.setBackground(new java.awt.Color(153, 153, 0));
        LeftPanel.setLayout(null);

        UserButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        UserButton.setText("User List");
        UserButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserButtonActionPerformed(evt);
            }
        });
        LeftPanel.add(UserButton);
        UserButton.setBounds(10, 220, 103, 30);

        ItemButton.setBackground(new java.awt.Color(153, 153, 153));
        ItemButton.setFont(new java.awt.Font("Trebuchet MS", 1, 11)); // NOI18N
        ItemButton.setText("Item Manager");
        LeftPanel.add(ItemButton);
        ItemButton.setBounds(10, 298, 98, 30);

        BuildNo.setText("PCBuild 0.7v");
        LeftPanel.add(BuildNo);
        BuildNo.setBounds(10, 680, 110, 16);

        MainMenuButton.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        MainMenuButton.setText("Main");
        LeftPanel.add(MainMenuButton);
        MainMenuButton.setBounds(10, 91, 103, 34);
        LeftPanel.add(jLabel1);
        jLabel1.setBounds(-6, -6, 160, 730);

        DynamicPanel.setBackground(new java.awt.Color(204, 204, 0));
        DynamicPanel.setMaximumSize(new java.awt.Dimension(1095, 720));
        DynamicPanel.setMinimumSize(new java.awt.Dimension(1095, 720));

        javax.swing.GroupLayout DynamicPanelLayout = new javax.swing.GroupLayout(DynamicPanel);
        DynamicPanel.setLayout(DynamicPanelLayout);
        DynamicPanelLayout.setHorizontalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1170, Short.MAX_VALUE)
        );
        DynamicPanelLayout.setVerticalGroup(
            DynamicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainpanelLayout = new javax.swing.GroupLayout(mainpanel);
        mainpanel.setLayout(mainpanelLayout);
        mainpanelLayout.setHorizontalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainpanelLayout.createSequentialGroup()
                .addComponent(LeftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        mainpanelLayout.setVerticalGroup(
            mainpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LeftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
            .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1296, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, Exception {
     conn =  SQLUtilities.DBConnection();  
     
     conn.setAutoCommit(false);
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
                SQLUtilities.Update_table(UserInfo.UserTable);
                SQLUtilities.Update_tableItem(ItemInfo.ItemTable);
               
             
            }
        });
    }
     
    
    protected String getCurrentItem;
    protected String getCurrentStock;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BuildNo;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JButton ItemButton;
    protected javax.swing.JPanel LeftPanel;
    private javax.swing.JButton MainMenuButton;
    private javax.swing.JButton UserButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainpanel;
    // End of variables declaration//GEN-END:variables
}
     

